import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="bg-slate-500 p-2 px-5 flex gap-5" />
        <Link href={"/dashboard"}>Dashboard Stall</Link>
        <Link href={"/blog"}>Blog Stall</Link>
        {children}
      </body>
    </html>
  );
}
